runtime: go
api_version: go1

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /child
  script: _go_app
  login: required
- url: /
  static_files: static/html/index.html
  upload: static/html/index\.html
  login: required
- url: /static
  static_dir: static
  login: required
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /browserconfig\.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig\.xml
- url: /manifest/.json
  static_files: static/manifest.json
  upload: static/manifest/.json
