runtime: go
api_version: go1

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /backup
  script: _go_app
  login: admin
- url: /api/(.*)
  script: _go_app
  login: required
- url: /node_modules
  static_dir: angular/node_modules
  login: required
- url: /styles.css
  static_files: angular/src/styles.css
  upload: angular/src/styles\.css
  login: required
- url: /systemjs-angular-loader.js
  static_files: angular/src/systemjs-angular-loader.js
  upload: angular/src/systemjs-angular-loader\.js
  login: required
- url: /systemjs.config.extras.js
  static_files: angular/src/systemjs.config.extras.js
  upload: angular/src/systemjs\.config\.extras\.js
  login: required
- url: /systemjs.config.js
  static_files: angular/src/systemjs.config.js
  upload: angular/src/systemjs\.config\.js
  login: required
- url: /main.js
  static_files: angular/src/main.js
  upload: angular/src/main\.js
  login: required
- url: /app
  static_dir: angular/src/app
  login: required
- url: /(.*)
  static_files: angular/src/index.html
  upload: angular/src/index\.html
  login: required  

