runtime: go
api_version: go1

skip_files:
 - .*node_modules$

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /createbackup
  script: _go_app
  login: admin
- url: /backup
  script: _go_app
  login: admin
- url: /api/(.*)
  script: _go_app
  login: required
- url: /styles.css
  static_files: angular/src/styles.css
  upload: angular/src/styles\.css
  login: required
- url: /inline.bundle.js
  static_files: angular/dist/inline.bundle.js
  upload: angular/dist/inline\.bundle\.js
  login: required
- url: /polyfills.bundle.js
  static_files: angular/dist/polyfills.bundle.js
  upload: angular/dist/polyfills\.bundle\.js
  login: required
- url: /styles.bundle.js
  static_files: angular/dist/styles.bundle.js
  upload: angular/dist/styles\.bundle\.js
  login: required
- url: /vendor.bundle.js
  static_files: angular/dist/vendor.bundle.js
  upload: angular/dist/vendor\.bundle\.js
  login: required
- url: /main.bundle.js
  static_files: angular/dist/main.bundle.js
  upload: angular/dist/main\.bundle\.js
  login: required
- url: /app
  static_dir: angular/src/app
  login: required
- url: /
  static_files: angular/dist/index.html
  upload: angular/dist/index\.html
  login: required  
- url: /(family/.*|locations|projects|services|search|consent)
  static_files: angular/dist/index.html
  upload: angular/dist/index\.html
  login: required  
- url: /(.*)
  script: _go_app
  login: required

