runtime: go
api_version: go1

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /backup
  script: _go_app
  login: required
- url: /
  static_files: static/html/record.html
  upload: static/html/record\.html
  login: required
- url: /consent
  static_files: static/html/consent.html
  upload: static/html/consent\.html
  login: required
- url: /search
  static_files: static/html/search.html
  upload: static/html/search\.html
  login: required
- url: /family
  static_files: static/html/family.html
  upload: static/html/family\.html
  login: required
- url: /locations
  static_files: static/html/locations.html
  upload: static/html/locations\.html
  login: required
- url: /projects
  static_files: static/html/projects.html
  upload: static/html/projects\.html
  login: required
- url: /static
  static_dir: static
  login: required
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /browserconfig\.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig\.xml
- url: /manifest/.json
  static_files: static/manifest.json
  upload: static/manifest/.json
- url: /(.*)
  script: _go_app
  login: required